apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  labels:
    app: ocr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: ocr
        image: ocr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: metrics
        envFrom:
        - configMapRef:
            name: ocr-services-config
        env:
        - name: METRICS_PORT
          value: "8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"